version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html   # Monta la raíz directamente
    env_file:
      - .env              # Si .env está en la raíz
